### ISSUE TITLE
Advanced ldap not working with ldaps server

### ISSUE THREAD

**Issue by mjbros** [dkoudela/advanced-ldap-for-crucible#4] opened 2015-11-11 09:32 UTC
I can't get this plugin to work with our LDAP server which uses ldaps

Fisheye is able to connect to the LDAP server without any issues.

This is the error message
**************************** AdvancedLdapConnector EXCEPTION ****************************LDAPException(resultCode=84 (decod                                           ed while waiting for a response to a bind request SimpleBindRequest(dn=''):  Unable to read or decode an LDAP message:  Inv                                            a length between 1 and 4 bytes.com.unboundid.asn1.ASN1Exception: Invalid value length of 0 for an ASN.1 integer element.
**************************** AdvancedLdapConnector On Finalize ****************************
**************************** AdvancedLdapConnector EXCEPTION on conn closed ****************************java.lang.NullPoint
AdvancedLdapUserManagerImpl.loadGroups END

**Comment by dkoudela** [comment] 2015-11-11 11:36
Hi,

Could you please confirm you have changed "Ldap Page Size" parameter to 10 ?

Thanks,
David.

**Comment by znoorsazali** [comment] 2015-11-18 19:03
Hi David,

I am investigating the issue together with Mike on the connection issue to ldaps. I configure Fisheye to try connecting to Jumpcloud ldaps, it doesn't work whilst Jumpcloud ldap works just fine.

Instead of hitting into 84 error, I hit into 81 error. See:

`AdvancedLdapUserManagerImpl.loadGroups START
LDAP Connection parameters: ldapHost: ldap.jumpcloud.com ldapPort: 636 ldapBindDN: uid=admin,ou=Users,o=564606909fb0746a7f000262,dc=jumpcloud,dc=com
**************************** AdvancedLdapConnector EXCEPTION ****************************LDAPException(resultCode=81 (server down), errorMessage='The connection to server ldap.jumpcloud.com:636 was closed while waiting for a response to a bind request SimpleBindRequest(dn='uid=admin,ou=Users,o=564606909fb0746a7f000262,dc=jumpcloud,dc=com').')
**************************** AdvancedLdapConnector On Finalize ****************************
**************************** AdvancedLdapConnector EXCEPTION on conn closed ****************************java.lang.NullPointerException
AdvancedLdapUserManagerImpl.loadGroups END`

I have my config on:
Server Timeout10000
Synchronise Period3600
Ldap Page Size99

Anything I might have missed?

**Comment by dkoudela** [comment] 2015-11-18 20:04
Hi,

Thank you very much for this information.
I will definitely try Jumpcloud ldaps against the plugin.
Hopefully, the errors have the same root cause. 

I will inform you about the progress.

Best Regards,
David.

**Comment by dkoudela** [comment] 2015-11-19 08:34
Hi,

I am sorry I am able to sync my users and groups with Jumpcloud :-(
I am not able to reproduce the same issue you have got.

I am attaching my settings.
I would appreciate if you can compare it with yours and tell me the difference.

I would like to reproduce it as it is annoying for customers.

Thanks and Best Regards,
David.

P.S.: I have re-designed the configuration page (preparation for the next release), so, it looks different but the content is the same (except one check-box).

![ldap jumpcloud01](https://cloud.githubusercontent.com/assets/7679620/11265726/fdffdb4e-8e9e-11e5-9846-a37198ed347c.png)

**Comment by znoorsazali** [comment] 2015-11-19 15:44
David,

Can you try using ldaps://ldap.jumpcloud.com (defaults to port 636) as per http://support.jumpcloud.com/knowledgebase/articles/474035-configuring-your-application-with-jumpcloud-ldap to try connecting using ldap secure. I also managed to get it working just find with just ldap.

The differences that I can see here are
* User display name attribute = displayName
* GID attribute = cn
* Group filter = objectClass=groupOfNames

I don't believe the schema settings is the problem since the error thrown is LDAP ERROR CODE 81 (server down) suggesting connectivity issue. Anyhow, I'll update the schema settings on my local and let you know by the end of today.

Thanks,

P/s: Nice new UI, loving it :+1:

**Comment by dkoudela** [comment] 2015-11-19 20:41
Hi, 

I see! That's the key! :+1: 
Thank you very much!

Now, I know where the problem is. The LDAP library does not manage SSL connections itself.
Fortunately, there is a way how to do it.

I am working on it.
I will inform you once I get a beta version available.

You are right. It is about SSL-Based Connection establishment.

Thank you very much!
David.

**Comment by dkoudela** [comment] 2015-11-19 21:49
Hi,

I have fixed this issue. I will release it together with the other features. 

Thank you very much for your cooperation!
David.

**Comment by dkoudela** [comment] 2015-11-22 20:39
Hi,

It has been released in:
https://github.com/dkoudela/advanced-ldap-for-crucible/releases/tag/v1.4

Thanks,
David.

**Closed** 2015-11-22 20:39 UTC
Labels: bug
